import { StyleSheet } from "react-native";
import colors from '../../../component/colors';
export default StyleSheet.create({
    container:{
        flexDirection:'row',
        justifyContent:'space-between',
        marginTop:38
    },
    imageView:{
        width:60,
        height:60,
        backgroundColor:colors.bc,
        borderRadius:30,
        justifyContent:'center',
        alignItems:'center'
    },
    text:{
        fontFamily:'Montserrat-Normal',
        fontSize:14,
        color:colors.textColor,
        marginTop:6,
        fontWeight:'600',
        textAlign: 'center',
    },
    name:{
        color:colors.white,
        fontSize:19,
        fontFamily:'Montserrat-Normal'
    },
    last:{
        color:colors.white,
        fontSize:13,
        fontFamily:'Montserrat-Normal'
    },
    pfile:{
        width:76,
        height:76,
        borderRadius:37,
        backgroundColor:'#fff',
        justifyContent:'center',
        alignItems:'center'
    },
    main:{
        height:165,
        width:'100%',
        backgroundColor:'#C4C4C4',
        justifyContent:'center',
        alignItems:'center'
    },
    image:{
        width:71,
        height:71,
    },
    item:{
        flex:1,
        marginBottom:20
    }
})
