import { StyleSheet ,Platform} from 'react-native';
import colors from '../../../component/colors';
import fontSize from '../../../component/fontSize';
export default StyleSheet.create({
    container1:
    {
        flex:1,
        backgroundColor:colors.card,
       // paddingTop:Platform.OS=='android'?0:40
    },
    list:
    {
        shadowColor:colors.black,
        shadowOpacity:0.25,
        shadowRadius:4,
        shadowOffset:{height:2,width:0},
        elevation:2,
        borderRadius:10,
        backgroundColor:colors.white,
        paddingVertical:15,
        marginHorizontal:15,
        justifyContent:'center',
        alignItems:'center',
        marginVertical:2,
       // marginTop:13
    },
    img:
    {
        width:86,
        height:30
    },
    Text1:
    {
        marginTop:10,
        fontSize:fontSize.fourteen,
        color:colors.bc,
        fontFamily:'Montserrat-Medium',
        width:'70%',
        textAlign:'center'
        
     },
     Text2:
     {
         marginTop:6,
         fontSize:fontSize.twelve,
         fontFamily:'Montserrat-Medium',
         color:colors.textColor
     },
    item:
    {
        fontSize:fontSize.ten,
        fontFamily:'Montserrat-Regular',
        color:colors.heading,
        // width:'100%'
    },
    item1:
    {
        fontSize:9,
        fontFamily:'Montserrat-Regular',
        color:colors.textColor
    },
    card:
    {
        backgroundColor:colors.white,
    },
    container:
    {
        flexDirection:'row',
        justifyContent:'space-between',
        paddingVertical:13,
        paddingHorizontal:12
    },
    tds:
    {
        color:colors.black,
        fontFamily:'Montserrat-Regular',
        marginTop:10
    },
    lorem:
    {
        color:colors.textColor,
        fontFamily:'Montserrat-Regular',
        marginTop:10,
        fontSize:fontSize.thirteen
    },
    point:
    {
        width:6,
        height:6,
        borderRadius:3,
        backgroundColor:colors.black,
        marginTop:7
    },
    pointText:
    {
        color:colors.textColor,
        fontFamily:'Montserrat-Regular',
        fontSize:fontSize.thirteen,
        marginLeft:10,
        marginTop:1
    },
    bank:
    {
        backgroundColor:colors.white,
        marginTop:13,
        paddingVertical:15,
        paddingHorizontal:50,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between'
    },
    bankDetails:
    {
        color:colors.bc,
        fontSize:fontSize.thirteen,
        fontFamily:'Montserrat-Regular',
        fontWeight:'700'
    },
    top:
    {
        backgroundColor:colors.white,
        marginTop:13,
        paddingVertical:15,
        paddingHorizontal:20
    },
    line:
    {
        borderWidth:1,
        borderColor:'#C7BEBE'
    },
    undercard:
    {
        alignItems:'center',
        width:'33%'
    },
    second:
    {
        backgroundColor:colors.white,
        marginTop:13
    },
    Textview:
    {
        marginTop:6,
        flexDirection:'row'
    },
    Text3:
    {
        color:colors.black,
        fontFamily:'Montserrat-Regular',
        marginTop:10
    },
    rupay:
    {
        marginRight:2,
        height:16,
        width:12,
        marginTop:2
    },
    rup:
    {
        flexDirection:'row',
        alignItems:'center'
    },
    btCont:
    {
        height:45,
        borderRadius:20,
        backgroundColor:colors.bc,
        alignItems:'center',
        justifyContent:'center',
        paddingHorizontal:6
    },
    text3:
    {
        color:colors.white,
        fontFamily:'Montserrat-Regular',
        fontSize:13
    },
    button:
    {
        flexDirection:'row',
        justifyContent:'space-between',
        paddingHorizontal:20,
        bottom:15,
        position:'absolute',
        left:0,
        right:0,
    },
})
