export default {
    user_id:'user_id',
    
    mobile:'mobile',
    name:'name',
    email:'email',
    dob:'dob',
    fatherName:'fatherName',
    motherName:'motherName',
    gender:'gender',
    photo:'photo',
    token:'token',
    image:'image',
    status:'status',
    pan:'pan',
    address1:'address1',
    address2:'address2',
    occupation:'occupation',
    pincode:'pincode',
    country:'country',
    state:'state',
    city:'city',
    income_group:'income_group',
    education:'education',
    marital:'marital',
    residential:'residential',
    cityId:'cityId',
    stateId:'stateId',
    // blow register refrence
    Rname:'Rname',
    Remail:'Remail',
    Rmobile:'Rmobile',
    RcountryCode:'RcountryCode',
    Rpin:'Rpin',
    Rreferal:'Rreferal'
}