import { StyleSheet } from 'react-native';
import colors from '../../../component/colors';
import fontSize from '../../../component/fontSize';
export default StyleSheet.create({
    container:{
    flex: 1,
    },
    imageContainer:{
        alignItems:'center',
        marginTop:20
    }, 
    textView:{
        justifyContent:'center',
        alignItems:'center',
        marginTop:30
    },
    text:{
        fontFamily:'Montserrat-SemiBold',
        color:colors.textColor,
        fontSize:fontSize.twenty
    },
    logo:{
        width:'80%',
        height:75,
        resizeMode:'stretch'
    },
    main:{
        paddingHorizontal:30,
        marginTop:60
    },
    main1:{marginTop:18},
    heading:{
        fontSize:fontSize.eighteen,
        color:colors.textColor,
        fontFamily:'Montserrat-Normal'
    },
    normal:{
        fontSize:fontSize.thirteen,
        fontFamily:'Montserrat-Normal',
        color:colors.textColor,
        marginTop:10,
        lineHeight:20
    },
    same:{
        fontFamily:'Montserrat-Medium',
        fontSize:fontSize.fefteen,
        color:colors.textColor
    },
    input:{
        marginTop:6,
        borderWidth:1,
        borderColor:colors.textColor,
        borderRadius:6,
        height:35,
        paddingHorizontal:10,
        justifyContent:'center'
    },
    textinput:{height:35,width:'90%',fontSize:fontSize.thirteen,color:colors.textColor},
    interest:{
        marginTop:6,
        borderWidth:1,
        borderColor:colors.textColor,
        borderRadius:6,
        height:35,
        paddingHorizontal:10,
        justifyContent:'space-between',
        flexDirection:'row',
        alignItems:'center'
    },
    buttonContainer:{
        marginTop:25,
        width:'100%',
        flexDirection:'row',
        justifyContent:'space-between',
        marginBottom:20
    },
    button:{
        width:'47%',
        height:45,
        borderRadius:30,
        backgroundColor:colors.textColor,
        alignItems:'center',
        justifyContent:'center'
    },
    cal:{
        color:colors.white,
        fontSize:fontSize.fourteen,
        fontFamily:'Montserrat-SemiBold'
    },
    drop:{
        marginTop:13 ,
        borderWidth:1,
        height:35,
        borderColor:colors.textColor,
        borderRadius:6,
        paddingHorizontal:10,
    },
    
   icon1:{marginTop:12,marginRight:5},
   view1:{flexDirection:'row',width:'100%'},
   view2:{flexDirection:'row',alignItems:'center',marginLeft:-5}, 
   text1:{color:colors.textColor,fontSize:fontSize.twelve},
})