import { StyleSheet ,Platform} from 'react-native';
import colors from '../../../component/colors';
import fontSize from '../../../component/fontSize';
export default StyleSheet.create({
    container1:
    {
        flex:1,
        backgroundColor:colors.card,
        //paddingTop:Platform.OS=='android'?0:40
    },
    img:
    {
        width:86,
        height:30
    },
    text:
    {
        marginTop:10,
        fontSize:fontSize.fourteen,
        color:colors.bc,
        fontFamily:'Montserrat-Medium',
        fontWeight:'600',
        width:'70%',
        textAlign:'center'
    },
    text1:
    {
        marginTop:6,
        fontSize:fontSize.twelve,
        fontFamily:'Montserrat-Medium',
        color:colors.textColor,
        fontWeight:'500'
    },
    list:
    {
        shadowColor:colors.black,
        shadowOpacity:0.25,
        shadowRadius:4,
        shadowOffset:{height:2,width:0},
        elevation:2,
        borderRadius:10,
        backgroundColor:colors.white,
        paddingVertical:15,
        marginHorizontal:15,
        justifyContent:'center',
        alignItems:'center',
        marginVertical:2,
        marginTop:13
    },
    item:
    {
        fontSize:fontSize.twelve,
        fontFamily:'Montserrat-Regular',
        color:colors.textColor
    },
    item1:
    {
        fontSize:fontSize.eleven,
        fontFamily:'Montserrat-Regular',
        color:colors.heading
    },
    view1:
    {
        backgroundColor:colors.white
    },
    container:
    {
        flexDirection:'row',
        justifyContent:'space-between',
        paddingVertical:13,
        paddingHorizontal:12
    },
    line:
    {
        borderWidth:1,
        borderColor:'#C7BEBE'
    },
    view3:
    {
        marginTop:6,
        flexDirection:'row'
    },
    view2:
    {
        alignItems:'center'
    },
    tds:
    {
        color:colors.black,
    fontFamily:'Montserrat-Regular',
    marginTop:10,
    fontWeight:'700',
    fontSize:fontSize.fourteen
},
    lorem:
    {
        color:colors.textColor,
        fontFamily:'Montserrat-Regular',
        marginTop:10,
        fontSize:fontSize.thirteen
    },
    point:
    {
        width:6,
        height:6,
        borderRadius:3,
        backgroundColor:colors.black,
        marginTop:7
    },
    pointText:
    {
        color:colors.textColor,
        fontFamily:'Montserrat-Regular',
        fontSize:fontSize.thirteen,
        marginLeft:10,
        marginTop:1
    },
    bank:
    {
        backgroundColor:colors.white,
        marginTop:13,
        paddingVertical:15,
        paddingHorizontal:50,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between'
       },
    text3:
    {
        color:colors.white,
        fontFamily:'Montserrat-Regular',
    },
    text2:
    {
        color:colors.black,
        fontFamily:'Montserrat-Regular',
        marginTop:10
    },
    bankDetails:
    {
        color:colors.bc,
        fontSize:fontSize.thirteen,
        fontFamily:'Montserrat-Regular',
        fontWeight:'700'
    },
    top:
    {
        backgroundColor:colors.white,
        marginTop:13,
        paddingVertical:15,
        paddingHorizontal:20
    },
    button:
    {
        flexDirection:'row',
        justifyContent:'space-between',
        paddingHorizontal:20,
        paddingVertical:20,
        marginBottom:20
    },
    btCont:
    {
        width:'47%',height:45,
        borderRadius:20,
        backgroundColor:colors.bc,
        alignItems:'center',
        justifyContent:'center'
    },
      rupay:
    {
        marginRight:2,
        height:11,
        width:8,
        marginTop:2
    },
    view4:{
        backgroundColor:colors.white,
        marginTop:13
    },
})
