import { StyleSheet } from 'react-native';
import colors from '../../../component/colors';

export default StyleSheet.create({
    same:{
        fontSize:11,
        fontFamily:'Montserrat-Normal',
        color:colors.textColor
    },
    title:{
        fontSize:14,
        fontFamily:'Montserrat-Normal',
        color:colors.textColor
    },
    cardView:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center'
    },
    card:{
        shadowColor:'black',
        shadowOpacity:0.25,
        shadowRadius:4,
        shadowOffset:{height:2,width:0},
        elevation:5,
        borderRadius:6,
        backgroundColor:'white',
        height:85,
        padding:13,
    },
    title1:{
        fontFamily:'Montserrat-Medium',
        color:colors.textColor
    },
    value1:{
        fontFamily:'Montserrat-Normal',
        fontSize:12,
        color:colors.textColor
    },
    cont:{
        paddingHorizontal:25,
        paddingVertical:8
    },
    align:{
        flexDirection:'row',
        justifyContent:'space-between',
    },
    border:{
        width:'100%',
        borderWidth:1,
        marginTop:12,
        borderColor:colors.textColor
    },
    list:{
        alignItems:'center',
        justifyContent:'center',
        flex:1,
        marginTop:10
    }
})
