import { StyleSheet } from 'react-native';
import colors from '../../../component/colors';

export default StyleSheet.create({
    container:{
    flex: 1,
    justifyContent: 'center',
    alignContent: 'center',
    },
   
    imageContainer:{
        alignItems:'center',
        marginTop:20
    },
    main:{
        paddingHorizontal:10,
        justifyContent:'center',
        alignItems:'center',
        marginTop:40
    },
    second:{
        width:'90%',
        height:40,
        borderWidth:1,
        justifyContent:'center',
        flexDirection:'row',
        borderRadius:6,
        borderColor:colors.textColor
    },
    imageView:{
        justifyContent:'center',
        alignItems:'center',
        width:40,
        height:'100%',
        borderRightWidth:1
    },
    input:{
        width:'87%',
        justifyContent:'center',
        alignItems:'flex-start',
        paddingHorizontal:10
    },
    textView:{
        justifyContent:'center',
        alignItems:'center',
        marginTop:30
    },
    text:{
        fontFamily:'Montserrat-SemiBold',
        color:colors.textColor,
        fontSize:22
    },
    main1:{
        height:40,
        width:'100%',
        flexDirection:'row',
        paddingHorizontal:12,
        alignItems:'center',
        justifyContent:'space-between'
    },
    check:{
        flexDirection:'row',
        alignItems:'center'
    },
    keep:{
        color:colors.textColor,
        fontSize:11
    },
    forgot:{
        marginRight:5,
        color:colors.textColor,
        fontSize:11
    },
    button:{
        width:'100%',
        paddingHorizontal:20,
        marginTop:10
    },
    bottom:{
        flexDirection:'row',
        marginTop:8,
        marginBottom:20
    },
    account:{
        color:colors.textColor,
        fontSize:13
    },
    inputContainerStyle: {
        height: 40,
        borderRadius: 6,
        backgroundColor: '#ffffff',
        borderWidth:1,
        width:'100%'
    },
    inputStyle:{
        fontSize: 14, 
        marginLeft: 10
    },
    view:{
        width:'100%',
        paddingHorizontal:20,
        marginTop:15
    },
    view1:{
        width:'100%',
        height:40,
        borderWidth:1,
        borderRadius:6,
        borderColor:colors.textColor,
        paddingHorizontal:14,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between'
    },
    view2:{
        width:'100%',
        height:40,
        borderWidth:1,
        borderRadius:6,
        borderColor:colors.textColor,
       
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between'
    },
    view3:{
        width:'88%',
        height:40,
        borderColor:colors.textColor,
        paddingHorizontal:10,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
    },
    error:{
        width:'90%',
        justifyContent:'center',
        alignItems:'flex-start',
        paddingHorizontal:0,
        marginTop:6
    },
    mobile:{
        borderRightWidth:1,
        height:40,
        width:40,
        justifyContent:'center',
        alignItems:'center',
        borderColor:colors.textColor
    },
    image:{
        width:'82%',
        height:75,
        resizeMode:'stretch'
    },
    mainCon:{
        paddingHorizontal:20,
        width:'100%'
    },
    input1:{
        width:'90%',
        color:colors.textColor
    },
    warn:{
        fontSize:14,
        color:'red'
    },
    input2:{
        width:'80%',
        color:colors.textColor
    }
   
})